kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: demo-jiva-replica-pinned
spec:
  storageClassName: openebs-jiva-nodeselector
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 4G

