kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: cstor-sc-sparse-tgt-debug
  annotations:
    cas.openebs.io/config: |
      - name: DebugProfile
        value: "cpu"
spec:
  storageClassName: openebs-cstor-sparse
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 4G
