kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: dbench-cstor-sparse1
spec:
  storageClassName: openebs-cstor-sparse1
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
---
apiVersion: batch/v1
kind: Job
metadata:
  name: dbench-cs
spec:
  template:
    spec:
      nodeSelector: 
        kubernetes.io/hostname: "gke-kmova-helm-default-pool-e23a1a84-k1n0"
      containers:
      - name: dbench
        image: logdna/dbench:latest
        imagePullPolicy: Always
        env:
          - name: DBENCH_MOUNTPOINT
            value: /data
          # - name: DBENCH_QUICK
          #   value: "yes"
          - name: FIO_SIZE
            value: 1G
          # - name: FIO_OFFSET_INCREMENT
          #   value: 256M
          # - name: FIO_DIRECT
          #   value: "0"
        volumeMounts:
        - name: dbench-pv
          mountPath: /data
      restartPolicy: Never
      volumes:
      - name: dbench-pv
        persistentVolumeClaim:
          claimName: dbench-cstor-sparse1
  backoffLimit: 4
