apiVersion: v1
kind: Pod
metadata:
  name: fio-test
  labels:
    name: fio-test
spec:
  containers:
  - name: fio-test
    image: openebs/tests-fio
    command: ["/bin/bash", "-ec", "while :; do echo '.'; sleep 60; done"]
    tty: true
    volumeMounts:
    - mountPath: /datadir
      name: datavol
  volumes:
    - name: datavol
      persistentVolumeClaim:
        claimName: demo-cstor-disk-vol1-claim
