---
apiVersion: openebs.io/v1alpha1
kind: StoragePoolClaim
metadata:
  name: test-pool
spec:
  name: cstor-disk
  type: disk
  maxPools: 1
  poolSpec:
    poolType: striped
---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: openebs-cstor-disk
  annotations:
    openebs.io/cas-type: cstor
    cas.openebs.io/config: |
      - name: StoragePoolClaim
        value: "test-pool"
provisioner: openebs.io/provisioner-iscsi
---
